# Generated by Django 2.1.7 on 2019-05-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('BITSID', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=1000)),
                ('Reason', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=254)),
                ('RequestDate', models.CharField(max_length=100)),
                ('ReturnDate', models.CharField(max_length=100)),
                ('Lecture1', models.CharField(choices=[('s', 'Sujjala Shetty'), ('p', 'priti bajpy'), ('sa', 'Santosh'), ('k', 'k.kumar')], max_length=100)),
                ('Lecture2', models.CharField(choices=[('s', 'Sujjala Shetty'), ('p', 'priti bajpy'), ('sa', 'Santosh'), ('k', 'k.kumar')], max_length=100)),
            ],
        ),
    ]
